<?php

return [
    'sectors' => [
        [
            'title' => 'Plastic Industry',
            'description' => 'The plastic industry is a global industry that produces a wide range of plastic products.',
            'thumbnail' => 'images/sectors/plastic-industry.png',
            'slug' => 'plastic-industry',
            'route' => 'sectors.show',
        ],
        [
            'title' => 'Flexible & Rigid Packaging',
            'description' => 'Flexible & rigid packaging is a global industry that produces a wide range of plastic products.',
            'thumbnail' => 'images/sectors/flexible-rigid-packaging.png',
            'slug' => 'flexible-rigid-packaging',
            'route' => 'sectors.show',
        ],
        [
            'title' => 'Other Types of Packaging',
            'description' => 'Other types of packaging is a global industry that produces a wide range of plastic products.',
            'thumbnail' => 'images/sectors/other-types-of-packaging.webp',
            'slug' => 'other-types-of-packaging',
            'route' => 'sectors.show',
        ],
        [
            'title' => 'Lithium Battery Recycling',
            'description' => 'Lithium battery recycling is the process of recycling lithium batteries.',
            'thumbnail' => 'images/sectors/lithium-battery-recycling.webp',
            'slug' => 'lithium-battery-recycling',
            'route' => 'sectors.show',
        ],
        [
            'title' => 'Renewable Energy',
            'description' => 'Renewable energy is energy that is collected from renewable resources, which are naturally replenished on a human timescale, such as sunlight, wind, rain, tides, waves, and geothermal heat.',
            'thumbnail' => 'images/sectors/renewable-energy.png',
            'slug' => 'renewable-energy',
            'route' => 'sectors.show',
        ],
        [
            'title' => 'Plastic Machinery',
            'description' => 'Plastic machinery is a global industry that produces a wide range of plastic products.',
            'thumbnail' => 'images/sectors/plastic-machinery.jpg',
            'slug' => 'plastic-machinery',
            'route' => 'sectors.show',
        ],
        [
            'title' => 'Packaging Machinery',
            'description' => 'Packaging machinery is a global industry that produces a wide range of plastic products.',
            'thumbnail' => 'images/sectors/packaging-machinery.jpg',
            'slug' => 'packaging-machinery',
            'route' => 'sectors.show',
        ],
        [
            'title' => 'Chemical Recycling',
            'description' => 'Chemical recycling is the process of recycling chemical products.',
            'thumbnail' => 'images/sectors/chemical-recycling.jpg',
            'slug' => 'chemical-recycling',
            'route' => 'sectors.show',
        ],
        [
            'title' => 'Solar Recycling',
            'description' => 'Solar recycling is the process of recycling solar panels.',
            'thumbnail' => 'images/sectors/solar-recycling.jpg',
            'slug' => 'solar-recycling',
            'route' => 'sectors.show',
        ],
        [
            'title' => 'Battery Recycling',
            'description' => 'Battery recycling is the process of recycling batteries.',
            'thumbnail' => 'images/sectors/battery-recycling.jpg',
            'slug' => 'battery-recycling',
            'route' => 'sectors.show',
        ],
        [
            'title' => 'Electric Mobility',
            'description' => 'Electric mobility is the use of electric vehicles for transportation.',
            'thumbnail' => 'images/sectors/electric-mobility.jpg',
            'slug' => 'electric-mobility',
            'route' => 'sectors.show',
        ],
        [
            'title' => 'Manufacturing',
            'description' => 'Manufacturing is the production of goods on a large scale.',
            'thumbnail' => 'images/sectors/manufacturing.jpg',
            'slug' => 'manufacturing',
            'route' => 'sectors.show',
        ],
        [
            'title' => 'Water Conservation',
            'description' => 'Efficient management, preservation, and sustainable use of water resources for long-term sustainability.',
            'thumbnail' => 'images/sectors/water-conservation.jpg',
            'slug' => 'water-conservation',
            'route' => 'sectors.show',
        ],
        [
            'title' => 'Waste Management',
            'description' => 'Systematic collection, processing, recycling, and disposal of waste for environmental sustainability.',
            'thumbnail' => 'images/sectors/waste-management.jpg',
            'slug' => 'waste-management',
            'route' => 'sectors.show',
        ],
        [
            'title' => 'Sustainability Leadership',
            'description' => 'Strategic vision integrating environmental, social, and economic responsibility into core business operations.',
            'thumbnail' => 'images/sectors/sustainability-leadership.jpg',
            'slug' => 'sustainability-leadership',
            'route' => 'sectors.show',
        ],
        [
            'title' => 'Start-Up Ecosystem',
            'description' => 'Innovation-driven entrepreneurial ventures with scalable business models and high growth potential.',
            'thumbnail' => 'images/sectors/start-up-ecosystem.jpg',
            'slug' => 'start-up-ecosystem',
            'route' => 'sectors.show',
        ],
        [
            'title' => 'Circular Economy',
            'description' => 'Economic model focused on minimizing waste, maximizing resource efficiency, and regenerating materials.',
            'thumbnail' => 'images/sectors/circular-economy.jpg',
            'slug' => 'circular-economy',
            'route' => 'sectors.show',
        ],
        [
            'title' => 'Corporate Social Responsibility',
            'description' => 'Ethical business commitment contributing to society, environment, and economic development.',
            'thumbnail' => 'images/sectors/csr.jpg',
            'slug' => 'csr',
            'route' => 'sectors.show',
        ],
        [
            'title' => 'Hydrogen Industry',
            'description' => 'Clean energy carrier for power generation, industrial processes, mobility, and global decarbonization.',
            'thumbnail' => 'images/sectors/hydrogen-industry.jpg',
            'slug' => 'hydrogen-industry',
            'route' => 'sectors.show',
        ],
        [
            'title' => 'Tyre & Rubber Recycling',
            'description' => 'Collection, processing, and repurposing of used tyres and rubber waste into reusable materials and energy.',
            'thumbnail' => 'images/sectors/tyre-rubber-recycling.jpg',
            'slug' => 'tyre-rubber-recycling',
            'route' => 'sectors.show',
        ],
        [
            'title' => 'Biofuel / Bio Energy',
            'description' => 'Renewable energy from biological and organic materials for power, transport, and industrial applications.',
            'thumbnail' => 'images/sectors/biofuel-bioenergy.jpg',
            'slug' => 'biofuel-bioenergy',
            'route' => 'sectors.show',
        ],
        [
            'title' => 'Biogas Industry',
            'description' => 'Renewable energy from anaerobic digestion of organic waste for power, heating, and clean fuel production.',
            'thumbnail' => 'images/sectors/biogas-industry.jpg',
            'slug' => 'biogas-industry',
            'route' => 'sectors.show',
        ],
        [
            'title' => 'E-Waste Recycling',
            'description' => 'Collection, dismantling, and recovery of valuable materials from discarded electronics and equipment.',
            'thumbnail' => 'images/sectors/e-waste-recycling.jpg',
            'slug' => 'e-waste-recycling',
            'route' => 'sectors.show',
        ],
        [
            'title' => 'Glass Recycling',
            'description' => 'Collecting, sorting, and re-melting waste glass into reusable raw material — 100% infinitely recyclable.',
            'thumbnail' => 'images/sectors/glass-recycling.jpg',
            'slug' => 'glass-recycling',
            'route' => 'sectors.show',
        ],
        [
            'title' => 'Non-Ferrous & Scrap Recycling',
            'description' => 'Collection, processing, and reuse of non-iron metals and industrial scrap into secondary raw materials.',
            'thumbnail' => 'images/sectors/non-ferrous-scrap-recycling.jpg',
            'slug' => 'non-ferrous-scrap-recycling',
            'route' => 'sectors.show',
        ],
        [
            'title' => 'Plastic Recycling',
            'description' => 'Processing waste plastics into reusable raw materials — reducing landfills and promoting circular economy.',
            'thumbnail' => 'images/sectors/plastic-recycling.jpg',
            'slug' => 'plastic-recycling',
            'route' => 'sectors.show',
        ],
    ]
];