@extends('layouts.website')
@section('title', 'Welcome to MSME Chamber of Commerce and Industry of India')
@section('content')
    @include('website.home.partials.hero')
    @include('website.home.partials.events')
    @include('website.home.partials.about')
    @include('website.home.partials.values')
    @include('website.home.partials.why_choose')
    @include('website.home.partials.services')
    @include('website.home.partials.sectors')
    @include('website.home.partials.awards')
    @include('website.home.partials.impact')
    @include('website.home.partials.membership')
    @include('website.home.partials.cta')
    @include('website.home.partials.popup')
@endsection